---
# Flavor List
#+-----------+-------+------+-------+
#| Name      |   RAM | Disk | VCPUs |
#+-----------+-------+------+-------+
#| p1.tiny   |   128 |   10 |     1 |
#| p1.medium |   512 |   10 |     1 |
#| c1.tiny   |  1024 |   40 |     1 |
#| c2.tiny   |  1024 |   40 |     2 |
#| c1.small  |  2048 |   40 |     1 |
#| c2.small  |  2048 |   40 |     2 |
#| c1.medium |  4096 |   40 |     2 |
#| c2.medium |  4096 |   40 |     4 |
#| c3.medium |  4096 |   40 |     6 |
#| c1.large  |  8192 |   40 |     4 |
#| c2.large  |  8192 |   40 |     8 |
#| m1.xlarge | 16384 |   40 |     8 |
#+-----------+-------+------+-------+

# Using Image ID d324da4b-b827-44fb-8331-bfad41a28aca instead of Ubuntu 16.04.3,
# because of conflicting names in the provider. OpenStack did it wrong.
- name: Ensure aeternity network environments
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure integration environment stack
      os_stack:
        name: ae-integration
        state: present
        wait: yes
        rollback: yes
        template: "../openstack/ae-environment.yml"
        parameters:
          env_name: integration
          meta_groups: "epoch,integration,tag_role_epoch,tag_env_integration"
          node_count: 3
          node_flavor: c1.medium
          image_name: "d324da4b-b827-44fb-8331-bfad41a28aca"
      tags:
        - integration-env

    - name: Ensure UAT environment stack
      os_stack:
        name: ae-uat
        state: present
        wait: yes
        rollback: yes
        template: "../openstack/ae-environment.yml"
        parameters:
          env_name: uat
          meta_groups: "epoch,uat,tag_role_epoch,tag_env_uat"
          node_count: 20
          node_flavor: c1.large
          image_name: "d324da4b-b827-44fb-8331-bfad41a28aca"
      tags:
        - uat-env

    - name: Ensure tester environment stack
      os_stack:
        name: ae-tester
        state: present
        wait: yes
        rollback: yes
        template: "../openstack/ae-environment.yml"
        parameters:
          env_name: tester
          meta_groups: "epoch,uat,tester,tag_role_epoch,tag_env_uat,tag_env_tester"
          node_count: 1
          node_flavor: c1.large
          image_name: "d324da4b-b827-44fb-8331-bfad41a28aca"
      tags:
        - tester-env

    - name: Ensure dev1 environment stack
      os_stack:
        name: ae-dev1
        state: present
        wait: yes
        rollback: yes
        template: "../openstack/ae-environment.yml"
        parameters:
          env_name: dev1
          meta_groups: "epoch,dev1,tag_role_epoch,tag_env_dev1"
          node_count: 2
          node_flavor: c1.medium
          image_name: "d324da4b-b827-44fb-8331-bfad41a28aca"
      tags:
        - dev1-env

    - name: Ensure dev2 environment stack
      os_stack:
        name: ae-dev2
        state: present
        wait: yes
        rollback: yes
        template: "../openstack/ae-environment.yml"
        parameters:
          env_name: dev2
          meta_groups: "epoch,dev2,tag_role_epoch,tag_env_dev2"
          node_count: 2
          node_flavor: c1.medium
          image_name: "d324da4b-b827-44fb-8331-bfad41a28aca"
      tags:
        - dev2-env

    - name: Ensure ae-uat-uswest2 environment stack
      cloudformation:
        stack_name: "ae-uat"
        state: "present"
        region: "us-west-2"
        disable_rollback: true
        template: "../aws/ae-environment.yml"
      args:
        template_parameters:
          EnvName: "uat"
          ApiPort: 3013
          NodeCount: 10
          AmiId: "ami-34a9364c" # AMI  ubuntu 16.04.3 with master user + python added.
          InstanceType: "m4.large"
